version: '3.2'
services:
    tomcat:
        image: x.coe.phuket.psu.ac.th:50003/tomcat
        ports:
            - 8080:8080
        volumes:
            - ./webapps:/usr/local/tomcat/webapps
            - ./conf:/usr/local/tomcat/conf
        container_name: tomcat
