version: '3.2'
services:
    tomcat:
        image: tomcat
        ports:
            - 8080:8080
        volumes:
            - ./webapps:/usr/local/tomcat/webapps
            - ./conf:/usr/local/tomcat/conf
        container_name: tomcat
